In [79]:
import numpy as np
import matplotlib.pyplot as plt
import sklearn as sk
import pandas as pd
%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [81]:
# Loading data from source
high = pd.read_csv('data/highp_finalresults.csv')
low = pd.read_csv('data/lowp_finalresults.csv')
high.head()

,ident,it,t,a(i),emegas(i),emepla(i)/emet,rplanet(i)/radtie,emestar,rc,qest,sigmag_0,emed,gama,apert,fpert,constmigI,emetal,taugas
0,0,199993,20000001.0,0.030237,0.004911,1.904923,1.9029824602178687,4.368174e+32,59.88237,1.110726,51.287674,0.13,1.0,0.3,1.0,0.1,0.07707,9268935.0
1,0,199993,20000001.0,0.818832,0.000238,1.642056,1.8150047639338782,4.368174e+32,59.88237,1.110726,51.287674,0.13,1.0,0.3,1.0,0.1,0.07707,9268935.0
2,0,199993,20000001.0,2.124022,0.000000,1.786051,1.8659921485803184,4.368174e+32,59.88237,1.110726,51.287674,0.13,1.0,0.3,1.0,0.1,0.07707,9268935.0
3,0,199993,20000001.0,5.123330,0.000000,0.843418,1.4538852266916131,4.368174e+32,59.88237,1.110726,51.287674,0.13,1.0,0.3,1.0,0.1,0.07707,9268935.0
4,0,199993,20000001.0,6.932367,0.000000,0.477013,1.2031125383842882,4.368174e+32,59.88237,1.110726,51.287674,0.13,1.0,0.3,1.0,0.1,0.07707,9268935.0

In [82]:
low.tail()

,ident,it,t,a(i),emegas(i),emepla(i)/emet,rplanet(i)/radtie,emestar,rc,qest,sigmag_0,emed,gama,apert,fpert,constmigI,emetal,taugas
31813,2974,199890,20000001.0,4.495716,0.0,0.594153,1.2944807364978042,4.092467e+32,50.698605,6.853647,9.907135,0.018,1.0,0.1,1.0,0.1,0.408212,7710610.5
31814,2974,199890,20000001.0,5.055471,0.0,0.374487,1.1100260808524707,4.092467e+32,50.698605,6.853647,9.907135,0.018,1.0,0.1,1.0,0.1,0.408212,7710610.5
31815,2974,199890,20000001.0,5.741148,0.0,0.254932,0.97674134618047792,4.092467e+32,50.698605,6.853647,9.907135,0.018,1.0,0.1,1.0,0.1,0.408212,7710610.5
31816,2974,199890,20000001.0,6.215687,0.0,0.111676,0.74183642795434679,4.092467e+32,50.698605,6.853647,9.907135,0.018,1.0,0.1,1.0,0.1,0.408212,7710610.5
31817,2974,199890,20000001.0,7.612730,0.0,0.064155,0.61682163672276424,4.092467e+32,50.698605,6.853647,9.907135,0.018,1.0,0.1,1.0,0.1,0.408212,7710610.5

In [52]:
high.describe()

,ident,it,t,a(i),emegas(i),emepla(i)/emet,emestar,rc,qest,sigmag_0,emed,gama,apert,fpert,constmigI,emetal,taugas
count,32465.000000,32465.000000,32465.0,32465.000000,3.246500e+04,32465.000000,3.246500e+04,32465.000000,32465.000000,32465.000000,32465.000000,32465.0,32465.0,32465.0,3.246500e+04,32465.000000,3.246500e+04
mean,1483.424457,197467.410966,20000001.0,3.400574,7.167241e+00,7.630333,5.749874e+32,45.545752,5.963431,32.194985,0.043325,1.0,0.3,1.0,1.000000e-01,-0.001367,3.801387e+06
std,859.799152,8122.269582,0.0,3.696724,2.198142e+02,219.589599,2.784088e+32,8.270644,4.245843,33.406671,0.039576,0.0,0.0,0.0,5.721900e-14,0.211647,2.503500e+06
min,0.000000,9292.000000,20000001.0,0.002813,0.000000e+00,0.050002,2.005149e+32,25.340290,1.007152,1.515903,0.003100,1.0,0.3,1.0,1.000000e-01,-0.688720,1.001011e+06
25%,739.000000,198311.000000,20000001.0,0.913345,0.000000e+00,0.098376,3.379212e+32,39.816555,2.955550,12.484508,0.019000,1.0,0.3,1.0,1.000000e-01,-0.145420,1.687664e+06
50%,1484.000000,199620.000000,20000001.0,2.140342,0.000000e+00,0.229774,5.161603e+32,44.740940,4.808668,21.058982,0.030000,1.0,0.3,1.0,1.000000e-01,0.000306,2.998146e+06
75%,2227.000000,199907.000000,20000001.0,4.670935,2.295691e-10,0.669832,7.774028e+32,50.544758,7.681329,39.672398,0.054000,1.0,0.3,1.0,1.000000e-01,0.143216,5.405266e+06
max,2974.000000,199999.000000,20000001.0,37.368091,1.963193e+04,19634.764964,1.198218e+33,91.153824,48.223476,372.454042,0.320000,1.0,0.3,1.0,1.000000e-01,0.774710,9.985367e+06

In [53]:
low.describe()

,ident,it,t,a(i),emegas(i),emepla(i)/emet,emestar,rc,qest,sigmag_0,emed,gama,apert,fpert,constmigI,emetal,taugas
count,31818.000000,31818.000000,31818.0,31818.000000,3.181800e+04,31818.000000,3.181800e+04,31818.000000,31818.000000,31818.000000,31818.000000,31818.0,31818.0,31818.0,3.181800e+04,31818.000000,3.181800e+04
mean,1483.921742,197203.880068,20000001.0,3.427210,9.246545e+00,9.686454,5.849130e+32,45.464044,5.840116,33.392593,0.044799,1.0,0.1,1.0,1.000000e-01,0.000018,3.872820e+06
std,858.855403,8603.353319,0.0,3.677722,3.013759e+02,301.194360,2.818730e+32,8.256636,4.190124,34.231217,0.040328,0.0,0.0,0.0,5.652512e-14,0.211657,2.531576e+06
min,0.000000,2219.000000,20000001.0,0.002920,0.000000e+00,0.050000,2.005149e+32,25.340290,1.007152,1.515903,0.003100,1.0,0.1,1.0,1.000000e-01,-0.688720,1.001011e+06
25%,744.000000,198116.000000,20000001.0,0.959344,0.000000e+00,0.099108,3.424640e+32,39.637379,2.885965,13.020100,0.019000,1.0,0.1,1.0,1.000000e-01,-0.144467,1.716790e+06
50%,1486.000000,199593.000000,20000001.0,2.174640,0.000000e+00,0.236658,5.265640e+32,44.679085,4.708793,22.150014,0.031000,1.0,0.1,1.0,1.000000e-01,0.001603,3.071022e+06
75%,2229.000000,199903.000000,20000001.0,4.676797,1.394413e-10,0.697109,7.960997e+32,50.480225,7.520444,41.050120,0.056000,1.0,0.1,1.0,1.000000e-01,0.144376,5.562984e+06
max,2974.000000,199998.000000,20000001.0,38.434044,2.533239e+04,25335.050144,1.198218e+33,91.153824,48.223476,372.454042,0.320000,1.0,0.1,1.0,1.000000e-01,0.774710,9.985367e+06

## Data handling 
---
Data are organized in such way that each observation represent a formed planet. We have to collapse data by planetary systems ($ident$). However before do this we should verify that variables don't have variation between systems (no with-in variation). Also, we must create the final variables to predict:

Varibles:

    1. Number of planets.
    2. Planets total mass.
    3. Mass efficiency.

Tasks:
    
    1.Verify no with-in variation.
    2.Create final varaibles.
    3.Collapse data by $ident$

### Some 
There is several variables in each dataFrame that don't give extra information because they don't have variance over the set, for example:
    * t 
    * gama
    * apert
    * fpert
    * constmigI
So we can drop it. Futhermore, we can ignore ident information because system identifier should not give any information about the dependet variables

In [83]:
def collapse_by_system(dataFrame):
    ident_systems = unique(dataFrame['ident'])
    num_systems = len(ident_systems)
    print('There is only '+str(num_systems),'non-empty observations (systems)')
    # Define a new Data Frame to store planetary systems information 
    dataFrame_systems = pd.DataFrame(np.nan, index = range(0,0), columns = dataFrame.columns ) 
    # 1. Getting the # of planets per system
    # 2. Getting the total mass of planets = (emepla/emet)
    # 3. Getting the mass efficiency = total_mass/emed
    num_planets = np.zeros(num_systems)
    solid_mass = np.zeros(num_systems)
    mass_efficiency = np.zeros(num_systems)
    for sys in range(0,num_systems):
        system = ident_systems[sys]
        actual = dataFrame[dataFrame['ident'] == system]
        num_planets[sys] = actual['ident'].count()
        solid_mass[sys] = sum(actual['emepla(i)/emet'])
        mass_efficiency[sys] = solid_mass[sys]/np.min(actual['emed'])
        dataFrame_systems.loc[sys,:] = actual.iloc[0,:]
    # Dropping final conditions
    #dataFrame_systems.drop(['emegas(i)','emepla(i)/emet','rplanet(i)/radtie','a(i)'], axis=1, inplace=True)
    
    dataFrame_systems['num_planets'] = num_planets
    dataFrame_systems['solid_mass'] = solid_mass
    dataFrame_systems['mass_efficiency'] = mass_efficiency
    
    Y_dataFrame = dataFrame_systems[['num_planets','solid_mass','mass_efficiency']]
    X_dataFrame = dataFrame_systems[['it', 'emestar', 'rc', 'qest', 'sigmag_0', 'emed', 'emetal','taugas']]
    return X_dataFrame, Y_dataFrame

In [84]:
X_high,Y_high = collapse_by_system(high)

There is only 2770 non-empty observations (systems)

In [88]:
X_low,Y_low = collapse_by_system(low)

There is only 2735 non-empty observations (systems)

In [90]:
X_low.describe()

,it,emestar,rc,qest,sigmag_0,emed,emetal,taugas
count,2735.000000,2.735000e+03,2735.000000,2735.000000,2735.000000,2735.000000,2735.000000,2.735000e+03
mean,194194.970384,5.695265e+32,45.421354,5.838231,34.365057,0.045797,-0.007140,4.029660e+06
std,18305.644893,2.841563e+32,8.217106,4.506940,36.359857,0.042637,0.214781,2.567946e+06
min,2219.000000,2.005149e+32,25.340290,1.007152,1.515903,0.003100,-0.688720,1.001011e+06
25%,197613.000000,3.259032e+32,39.633905,2.790076,12.277057,0.018000,-0.153433,1.802566e+06
50%,199618.000000,5.038946e+32,44.677814,4.558093,22.402527,0.032000,-0.003980,3.325364e+06
75%,199911.000000,7.763991e+32,50.422327,7.475441,42.768552,0.057000,0.138821,5.837376e+06
max,199998.000000,1.198218e+33,91.153824,48.223476,372.454042,0.320000,0.774710,9.985367e+06

In [60]:
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn import preprocessing

In [86]:
X_train_high, X_test_high, Y_train_high, Y_test_test = train_test_split(X_high,Y_high)
X_train_low, X_test_low, Y_train_low, Y_test_low = train_test_split(X_low,Y_low)